apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - compliance.openeuler.org
      secretName: compliance-openeuler-org
  rules:
    - host: compliance.openeuler.org
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: front-cluster-ip
                port:
                  number: 80
          - pathType: Prefix
            path: /graphql
            backend:
              service:
                name: back-cluster-ip
                port:
                  number: 8080
          - pathType: Prefix
            path: /api_test
            backend:
              service:
                name: back-cluster-ip
                port:
                  number: 8080
          - pathType: Prefix
            path: /ci
            backend:
              service:
                name: wrapper-cluster-ip
                port:
                  number: 8081
          - pathType: Prefix
            path: /github_redirect
            backend:
              service:
                name: back-cluster-ip
                port:
                  number: 8080
          - pathType: Prefix
            path: /gitee_redirect
            backend:
              service:
                name: back-cluster-ip
                port:
                  number: 8080
          - pathType: Prefix
            path: /es_endpoint
            backend:
              service:
                name: wrapper-cluster-ip
                port:
                  number: 8081
          - pathType: Prefix
            path: /lvmeng
            backend:
              service:
                name: lvmeng-cluster-ip
                port:
                  number: 8080
          - pathType: Prefix
            path: /search_conflict
            backend:
              service:
                name: compatiable-cluster-ip
                port:
                  number: 5000
